# Generated by Django 3.0.5 on 2020-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_rating', models.FloatField()),
                ('book_img_src', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_year', models.IntegerField()),
                ('movie_genre', models.TextField()),
                ('movie_director', models.CharField(max_length=255)),
                ('movie_stars', models.TextField()),
                ('movie_rating', models.FloatField()),
                ('movie_oscar', models.CharField(max_length=10)),
                ('movie_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=255)),
                ('show_year', models.IntegerField()),
                ('show_genre', models.TextField()),
                ('show_stars', models.TextField()),
                ('show_rating', models.FloatField()),
            ],
        ),
    ]
